# Generated by Django 6.0.3 on 2026-07-26 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_customuser_managers_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='lenguaje',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor'),
        ),
    ]
