# Generated by Django 6.0.3 on 2026-08-04 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_autor_options_alter_genero_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_portada/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='imgqr',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_qr/'),
        ),
        migrations.AddField(
            model_name='libroinstancia',
            name='imgqr',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_qr/'),
        ),
        migrations.AddField(
            model_name='libroinstancia',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_portada/'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='librosx', to='catalogo.autor'),
        ),
    ]
