# Generated by Django 6.0.3 on 2026-08-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_libro_foto_libro_imgqr_libroinstancia_imgqr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='imgqr',
        ),
    ]
