# Generated by Django 6.0.3 on 2026-05-01 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['id']},
        ),
    ]
