# Generated by Django 4.1.4 on 2025-11-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libroinstancia',
            options={'ordering': ['debidoderegresar'], 'permissions': (('puedeMarcarRetornado', 'Tiene permiso para marcar libro como retornado'),)},
        ),
    ]
